using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Models
{
    public class VasbyhemData
    {
        public string DocumentName { get; set; }
        public string DocumentType { get; set; }
        public string DocumentOwner { get; set; } 
        public string AvdelningEnhet { get; set; }
        public string Klassificering { get; set; }
        public string Process { get; set; }
        public string Sekretess { get; set; }
        public string ISOStandard { get; set; } 

        public static List<VasbyhemData> InitData()
        {
            List<VasbyhemData> ret = new List<VasbyhemData>() {
/*new VasbyhemData("1.1 Övergripande styrprocess Ledning, beskrivning.docx","Dokumentmall","Jenny.RudSel@vasbyhem.se","HR, Marknad ＆ Hållbarhet","K0 - Allmän","","",""),
new VasbyhemData("1.1.1 Delprocess Företagsutveckling, beskrivning.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("2.1 Styrprocess Mål, strategier och policyer, beskrivning.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("2.2 Styrprocess Budget, beskrivning.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("2.3 Styrprocess Kvalitets- och miljöledning, beskrivning.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("2.3.1 Delprocess Ledningens genomgång, beskrivning.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("2.3.2 Delprocess Intern revision, beskrivning.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("2.4 Styrprocess Bindande krav, beskrivning.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("2.5 Styrprocess Personal, beskrivning.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("2.6 Styrprocess Kommunikation, beskrivning.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("3.1 Huvudprocess Byggnation, beskrivning.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("3.1.1 Delprocess Tidiga skeden, beskrivning.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("3.1.2 Delprocess Projektering, beskrivning.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("3.1.3 Delprocess Produktion, beskrivning.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("3.1.3.2 Miljömål och handlingsplaner på Väsbyhem.docx","Dokumentmall","Azarina.Backstrom@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("3.1.4 Delprocess Överlämning, beskrivning.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("3.1.4.2 Punkter på Ledningens genomgång, 190328.xlsx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("3.2 Huvudprocess Uthyrning, beskrivning.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("3.2.1 Delprocess Uthyrning bostad, beskrivning.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("3.2.2 Delprocess Uthyrning lokal, beskrivning.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("3.2.3 Delprocess Uthyrning P-plats, beskrivning.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("3.3 Huvudprocess Förvaltning, beskrivning.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("3.3.1 Delprocess Avflytt och inflytt, beskrivning.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("3.3.2 Delprocess Ärendehantering, beskrivning.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("4.1 Stödprocess Bokslut, beskrivning.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("4.2 Stödprocess Prognos, beskrivning.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("5.1.1 Verksamhetsledningssystem AB Väsbyhem.docx","Dokumentmall","Jenny.RudSel@vasbyhem.se","HR, Marknad ＆ Hållbarhet","K0 - Allmän","","",""),
new VasbyhemData("5.1.2 Företagsövergripande regler.docx","Dokumentmall","Jenny.RudSel@vasbyhem.se","HR, Marknad ＆ Hållbarhet","K0 - Allmän","","",""),
new VasbyhemData("5.2.1 Alkoholpolicy.docx","Policy","Jenny.RudSel@vasbyhem.se","HR, Marknad ＆ Hållbarhet","K0 - Allmän","","",""),
new VasbyhemData("5.2.1 Arbetsmiljöpolicy.docx","Policy","Jenny.RudSel@vasbyhem.se","HR, Marknad ＆ Hållbarhet","K0 - Allmän","","",""),
new VasbyhemData("5.2.1 Dataskyddspolicy GDPR.docx","Policy","Jenny.RudSel@vasbyhem.se","HR, Marknad ＆ Hållbarhet","K0 - Allmän","","",""),
new VasbyhemData("5.2.1 Dokumenthanteringspolicy.docx","Policy","Jenny.RudSel@vasbyhem.se","HR, Marknad ＆ Hållbarhet","K0 - Allmän","","",""),
new VasbyhemData("5.2.1 Finanspolicy.docx","Policy","Jenny.RudSel@vasbyhem.se","HR, Marknad ＆ Hållbarhet","K0 - Allmän","","",""),
new VasbyhemData("5.2.1 IT-policy.docx","Policy","Jenny.RudSel@vasbyhem.se","HR, Marknad ＆ Hållbarhet","K0 - Allmän","","",""),
new VasbyhemData("5.2.1 Jävpolicy.docx","Policy","Jenny.RudSel@vasbyhem.se","HR, Marknad ＆ Hållbarhet","K0 - Allmän","","",""),
new VasbyhemData("5.2.1 Mångfaldspolicy.docx","Policy","Jenny.RudSel@vasbyhem.se","HR, Marknad ＆ Hållbarhet","K0 - Allmän","","",""),
new VasbyhemData("5.2.1 Personalpolicy.docx","Policy","Jenny.RudSel@vasbyhem.se","HR, Marknad ＆ Hållbarhet","K0 - Allmän","","",""),
new VasbyhemData("5.2.1 Policy för sponsring och samverkan.docx","Policy","Jenny.RudSel@vasbyhem.se","HR, Marknad ＆ Hållbarhet","K0 - Allmän","","",""),
new VasbyhemData("5.2.1 Policy mot mutor.docx","Policy","Jenny.RudSel@vasbyhem.se","HR, Marknad ＆ Hållbarhet","K0 - Allmän","","",""),
new VasbyhemData("5.2.1 Resepolicy.docx","Policy","Jenny.RudSel@vasbyhem.se","HR, Marknad ＆ Hållbarhet","K0 - Allmän","","",""),
new VasbyhemData("5.2.1 Säkerhetspolicy.docx","Policy","Jenny.RudSel@vasbyhem.se","HR, Marknad ＆ Hållbarhet","K0 - Allmän","","",""),
new VasbyhemData("5.2.1 Upphandlingspolicy.docx","Policy","Jenny.RudSel@vasbyhem.se","HR, Marknad ＆ Hållbarhet","K0 - Allmän","","",""),
new VasbyhemData("5.2.1 Uthyrningspolicy.docx","Policy","Jenny.RudSel@vasbyhem.se","HR, Marknad ＆ Hållbarhet","K0 - Allmän","","",""),
new VasbyhemData("5.2.1 Verksamhetspolicy.docx","Policy","Jenny.RudSel@vasbyhem.se","HR, Marknad ＆ Hållbarhet","K0 - Allmän","","",""),
new VasbyhemData("5.3.2 Miljömål och handlingsplaner på Väsbyhem.docx","Dokumentmall","Azarina.Backstrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.1.1 Riktlinjer Alkohol och droger.docx","Riktlinje","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.1.1 Riktlinjer Arbetskläder.docx","Riktlinje","Daniel.Aronson@vasbyhem.se","Förvaltningsområde Centrala ","K0 - Allmän","","",""),
new VasbyhemData("6.1.1 Riktlinjer Bisysslor.docx","Riktlinje","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.1.1 Riktlinjer Brandskydd.docx","Riktlinje","johan.liderfors@vasbyhem.se","Fastighetsutveckling","K0 - Allmän","","",""),
new VasbyhemData("6.1.1 Riktlinjer Distans- och kontorsarbete .docx","Riktlinje","Victoria.brantestrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.1.1 Riktlinjer Elsäkerhet.docx","Riktlinje","johan.liderfors@vasbyhem.se","Fastighetsutveckling","K0 - Allmän","","",""),
new VasbyhemData("6.1.1 Riktlinjer examensarbete.docx","Riktlinje","Victoria.brantestrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.1.1 Riktlinjer Extern kommunikation.docx","Riktlinje","Jenny.RudSel@vasbyhem.se","HR, Marknad ＆ Hållbarhet ","K0 - Allmän","","",""),
new VasbyhemData("6.1.1 Riktlinjer för första hjälpen och krisstöd.docx","Riktlinje","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.1.1 Riktlinjer för visselblåsarfunktionen.docx","Riktlinje","sofi.sterner@vasbyhem.se","Affärsstöd Stab","K0 - Allmän","","",""),
new VasbyhemData("6.1.1 Riktlinjer Hantering av jäv.docx","Riktlinje","sofi.sterner@vasbyhem.se","Affärsstöd Stab","K0 - Allmän","","",""),
new VasbyhemData("6.1.1 Riktlinjer Hantering IT-utrustning och system.docx","Riktlinje","Julia.Hammar@vasbyhem.se","Affärsstöd Stab","K0 - Allmän","","",""),
new VasbyhemData("6.1.1 Riktlinjer Hälsogruppen.docx","Riktlinje","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.1.1 Riktlinjer Intern kommunikation.docx","Riktlinje","Jenny.RudSel@vasbyhem.se","HR, Marknad ＆ Hållbarhet ","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.1.1 Riktlinjer Introduktion av nyanställd.docx","Riktlinje","Victoria.brantestrom@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.1.1 Riktlinjer Kompetens, utbildning och medvetenhet i miljöarbetet på Väsbyhem.docx","Riktlinje","Azarina.Backstrom@vasbyhem.se","HMH Stab","K0 - Allmän","","","14001"),
new VasbyhemData("6.1.1 Riktlinjer Kompetensutveckling och utbildning.docx","Riktlinje","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.1.1 Riktlinjer Konferenser.docx","Riktlinje","Frida.Bodin@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.1.1 Riktlinjer Kränkande särbehandling.docx","Riktlinje","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001"),
new VasbyhemData("6.1.1 Riktlinjer Lönesättning.docx","Riktlinje","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.1.1 Riktlinjer Mentoruppdrag.docx","Riktlinje","Victoria.brantestrom@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001"),
new VasbyhemData("6.1.1 Riktlinjer Mot mutor.docx","Riktlinje","sofi.sterner@vasbyhem.se","Affärsstöd Stab","K0 - Allmän","","",""),
new VasbyhemData("6.1.1 Riktlinjer Offentlighetsprincipen.docx","Riktlinje","sofi.sterner@vasbyhem.se","Affärsstöd Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.1.1 Riktlinjer Omvärldsbevakning.docx","Riktlinje","hanna.nyberg@vasbyhem.se","Förvaltning Stab","K0 - Allmän","","",""),
new VasbyhemData("6.1.1 Riktlinjer Personalbil.docx","Riktlinje","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.1.1 Riktlinjer Policy.docx","Riktlinje","hanna.nyberg@vasbyhem.se","Förvaltning Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.1.1 Riktlinjer Representation.docx","Riktlinje","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.1.1 Riktlinjer Representation.docx","Riktlinje","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.1.1 Riktlinjer Telefoni.docx","Riktlinje","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.1.1 Riktlinjer Trafiksäkerhet.docx","Riktlinje","Ulf.Larsen@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.1.1 Riktlinjer Väsbyhems arbete mot våld i nära relation.docx","Riktlinje","Therese.Fleetwood@vasbyhem.se","Trygghet ＆ Säkerhet","K0 - Allmän","","",""),
new VasbyhemData("6.10.1 Rutin för hantering av kemiska produkter.docx","Rutin","Azarina.Backstrom@vasbyhem.se","HMH Stab","K0 - Allmän","","","14001"),
new VasbyhemData("6.10.1.1 Nya kemikalier (blankett).doc","Blankett","Azarina.Backstrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.10.1.2 Inventeringsschema för kemikalieskåp fr o m 2012.xlsx","Dokumentmall","Azarina.Backstrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.10.1.3 Förteckning över kemikalieskåp och ansvariga.docx","Dokumentmall","Azarina.Backstrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.10.1.4 Delegering av ansvar för kemikalieskåp med tillhörande pärm.docx","Dokumentmall","Azarina.Backstrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.10.10 Rutin Minskad avfallsmängd.docx","Rutin","Azarina.Backstrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.10.11 Rutin för bränslehantering.docx","Rutin","Jenny.Welch@vasbyhem.se","Utemiljö","K0 - Allmän","","",""),
new VasbyhemData("6.10.12 Rutin för klimatkompensation.docx","Rutin","Azarina.Backstrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.10.13 Hantering av oljeavskiljare Hammarbyväg 18.docx","Rutin","Ulf.Larsen@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.10.2 Kemikalieförteckning AB Väsbyhem.xlsx","Dokumentmall","Azarina.Backstrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.10.4 Rutin för avfallshantering.docx","Rutin","Daniel.Aronson@vasbyhem.se","Förvaltningsområde Centrala","K0 - Allmän","","",""),
new VasbyhemData("6.10.4.1 Transportdokument för farligt avfall (blankett).docx","Blankett","Azarina.Backstrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.10.5 Identifiering och värdering av miljöaspekter.docx","Rutin","Azarina.Backstrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.10.6 Miljöaspektregister.docx","Dokumentmall","Azarina.Backstrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.10.7 Betydande miljöaspekter på Väsbyhem.docx","Dokumentmall","Azarina.Backstrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.10.8 Rutin för olje- och fettavskiljare.docx","Rutin","Jenny.Welch@vasbyhem.se","Utemiljö","K0 - Allmän","","",""),
new VasbyhemData("6.10.9 Rutin Minskad energianvändning.docx","Rutin","Azarina.Backstrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.11.1 Beredskap och agerande vid nödlägen.docx","Rutin","Azarina.Backstrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.11.2 Riskanalys av nödlägessituationer.xlsx","Dokumentmall","Azarina.Backstrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.11.3 Förteckning över nödlägen som kräver styrning.docx","Rutin","Azarina.Backstrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.11.4 Rutin brand och utrymning Centralvägen 1.docx","Rutin","Ulf.Larsen@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.11.6 Krisledningsplan.docx","Rutin","Peyman.Rezapour@vasbyhem.se","Trygghet ＆ Säkerhet","K0 - Allmän","","",""),
new VasbyhemData("6.11.6.1 Larmlista krisledning.docx","Rutin","Peyman.Rezapour@vasbyhem.se","Trygghet ＆ Säkerhet","K0 - Allmän","","",""),
new VasbyhemData("6.11.8 Tillbudsrapport vid brand (blankett).doc","Blankett","Ulf.Larsen@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.11.9 Rutin Kontaktperson jour.docx","Rutin","johan.liderfors@vasbyhem.se","Fastighetsutveckling","K0 - Allmän","","",""),
new VasbyhemData("6.12.1 Rutin Hot och våld.docx","Rutin","Therese.Fleetwood@vasbyhem.se","Trygghet ＆ Säkerhet","K0 - Allmän","","",""),
new VasbyhemData("6.12.2 Rutin Utkvittering av personlarm.docx","Rutin","Daniel.Aronson@vasbyhem.se","Förvaltningsområde Centrala","K0 - Allmän","","",""),
new VasbyhemData("6.12.4 Beställning FöretagsID-kort (blankett).docx","Blankett","linda.selberg@vasbyhem.se","Kundcenter","K0 - Allmän","","",""),
new VasbyhemData("6.12.7 Fullmakt för åtkomst till nyckelskåp och uthämtning av elektroniska och mekaniska nycklar.docx","Blankett","linda.selberg@vasbyhem.se","Kundcenter","K0 - Allmän","","",""),
new VasbyhemData("6.13.1 Rutin Inköp och upphandling.docx","Rutin","sofi.sterner@vasbyhem.se","Affärsstöd Stab","K0 - Allmän","","",""),
new VasbyhemData("6.13.1.1 Beslutsunderlag för direktupphandling (blankett).docx","Blankett","sofi.sterner@vasbyhem.se","Affärsstöd Stab","K0 - Allmän","","",""),
new VasbyhemData("6.13.2 Rutin för Mindre inköp och utlägg.docx","Rutin","linda.selberg@vasbyhem.se","Kundcenter","K0 - Allmän","","",""),
new VasbyhemData("6.13.3 Checklista för miljökrav i upphandlingar.docx","Checklista","Azarina.Backstrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.13.4 Rutin Avtalshantering.docx","Rutin","sofi.sterner@vasbyhem.se","Affärsstöd Stab","K0 - Allmän","","",""),
new VasbyhemData("6.13.5 Rutin Beställning av personalbil LeasePlan via Benify.docx","Rutin","Sari.Auvinen@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.13.5.1 Föraravtal Personalbil.docx","Rutin","Sari.Auvinen@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.13.6 Rutin Inköp från Coop.docx","Rutin","linda.selberg@vasbyhem.se","Kundcenter","K0 - Allmän","","",""),
new VasbyhemData("6.14.1 Rutin Ersättning privata utlägg.docx","Rutin","Sari.Auvinen@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.14.10 Rutin Systemdokumentation och behandlingshistorik.docx","Rutin","Annsofie.Lindblad@vasbyhem.se","Redovisning ＆ Ekonomi","K0 - Allmän","","",""),
new VasbyhemData("6.14.3 Kreditering av kundfaktura (blankett) objekt XXXX-XXXX.xlsx","Dokumentmall","Ulrica.Nordeberg@vasbyhem.se","Redovisning ＆ Ekonomi","K0 - Allmän","","",""),
new VasbyhemData("6.14.4 Fakturaunderlag vidarefakturering till kund (blankett) objekt XXXX-XXXX.xlsx","Dokumentmall","Ulrica.Nordeberg@vasbyhem.se","Redovisning ＆ Ekonomi","K0 - Allmän","","",""),
new VasbyhemData("6.14.5 Avtal Men i boende (blankett) Objekt XXXX-XXXX.xlsx","Dokumentmall","Ulrica.Nordeberg@vasbyhem.se","Redovisning ＆ Ekonomi","K0 - Allmän","","",""),
new VasbyhemData("6.14.6  Avgiftsförändring (Blankett) objekt XXXX-XXXX.xlsx","Dokumentmall","Ulrica.Nordeberg@vasbyhem.se","Redovisning ＆ Ekonomi","K0 - Allmän","","",""),
new VasbyhemData("6.14.7 Rutin Bokförinsgorder och kontroll av verifiaktioner.docx","Rutin","Annsofie.Lindblad@vasbyhem.se","Redovisning ＆ Ekonomi","K0 - Allmän","","",""),
new VasbyhemData("6.14.8 Rutin Behörigheter inom redovisning och ekonomi.docx","Rutin","Annsofie.Lindblad@vasbyhem.se","Redovisning ＆ Ekonomi","K0 - Allmän","","",""),
new VasbyhemData("6.14.9 Rutin Attest.docx","Rutin","Annsofie.Lindblad@vasbyhem.se","Redovisning ＆ Ekonomi","K0 - Allmän","","",""),
new VasbyhemData("6.15.1 Klotter.docx","Rutin","Alexander.Gustafsson@vasbyhem.se","Förvaltningsområde Väst","K0 - Allmän","","",""),
new VasbyhemData("6.15.1 Klotter.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.10 Rondering Belysning.docx","Rutin","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.10 Rondering Belysning.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.11 Beställning externt.docx","Rutin","Daniel.Aronson@vasbyhem.se","Förvaltningsområde Centrala","K0 - Allmän","","",""),
new VasbyhemData("6.15.11 Beställning externt.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.13 Bomöte.docx","Rutin","Daniel.Aronson@vasbyhem.se","Förvaltningsområde Centrala","K0 - Allmän","","",""),
new VasbyhemData("6.15.14 Cykelrensning.docx","Rutin","Alexander.Gustafsson@vasbyhem.se","Förvaltningsområde Väst","K0 - Allmän","","",""),
new VasbyhemData("6.15.15 Rondering Drift.docx","Rutin","Nicklas.Chrysong@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.15.16 Driftstörning.docx","Rutin","Nicklas.Chrysong@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.15.18 Tömma felaktigt tagna eller kvarlämnade förråd.docx","Rutin","Alexander.Gustafsson@vasbyhem.se","Förvaltningsområde Väst","K0 - Allmän","","",""),
new VasbyhemData("6.15.19 Felanmälan ute.docx","Rutin","Alexander.Gustafsson@vasbyhem.se","Förvaltningsområde Väst","K0 - Allmän","","",""),
new VasbyhemData("6.15.2 Is och snö.docx","Rutin","Jenny.Welch@vasbyhem.se","Utemiljö","K0 - Allmän","","",""),
new VasbyhemData("6.15.20 Felanmälan via webb.docx","Rutin","Daniel.Aronson@vasbyhem.se","Förvaltningsområde Centrala","K0 - Allmän","","",""),
new VasbyhemData("6.15.21 Felanmälan via mejl och telefon.docx","Rutin","Daniel.Aronson@vasbyhem.se","Förvaltningsområde Centrala","K0 - Allmän","","",""),
new VasbyhemData("6.15.22 Felparkerade bilar och bortforsling.docx","Rutin","Alexander.Gustafsson@vasbyhem.se","Förvaltningsområde Väst","K0 - Allmän","","",""),
new VasbyhemData("6.15.23 Förrådsskötsel.docx","Rutin","Daniel.Aronson@vasbyhem.se","Förvaltningsområde Centrala","K0 - Allmän","","",""),
new VasbyhemData("6.15.24 Garanti.docx","Rutin","Stina.KjetselbergSalmen@vasbyhem.se","Förvaltning Stab","K0 - Allmän","","",""),
new VasbyhemData("6.15.25 Infoblad.docx","Rutin","Daniel.Aronson@vasbyhem.se","Förvaltningsområde Centrala","K0 - Allmän","","",""),
new VasbyhemData("6.15.28 Kalla lägenheter.docx","Rutin","Linus.Hagestal@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.15.29 Klagomålshantering.docx","Rutin","Daniel.Aronson@vasbyhem.se","Förvaltningsområde Centrala","K0 - Allmän","","",""),
new VasbyhemData("6.15.3 Besiktning vid avflytt.docx","Rutin","Eddie.Laakso@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.15.30 Kontroll av faktura.docx","Rutin","Alexander.Gustafsson@vasbyhem.se","Förvaltningsområde Väst","K0 - Allmän","","",""),
new VasbyhemData("6.15.32 Lappar.docx","Rutin","Alexander.Gustafsson@vasbyhem.se","Förvaltningsområde Väst","K0 - Allmän","","",""),
new VasbyhemData("6.15.33 Låsbyte.docx","Rutin","Magnus.Andersson@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.15.34 Misstanke om dödsfall.docx","Rutin","Daniel.Aronson@vasbyhem.se","Förvaltningsområde Centrala","K0 - Allmän","","",""),
new VasbyhemData("6.15.37 Obehörig i allmänna utrymmen.docx","Rutin","Daniel.Aronson@vasbyhem.se","Förvaltningsområde Centrala","K0 - Allmän","","",""),
new VasbyhemData("6.15.38 Paraboler.docx","Rutin","Alexander.Gustafsson@vasbyhem.se","Förvaltningsområde Väst","K0 - Allmän","","",""),
new VasbyhemData("6.15.39 Rondering Kvartersvärd.docx","Rutin","Daniel.Aronson@vasbyhem.se","Förvaltningsområde Centrala","K0 - Allmän","","",""),
new VasbyhemData("6.15.4 Servicetid .docx","Rutin","Daniel.Aronson@vasbyhem.se","Förvaltningsområde Centrala","K0 - Allmän","","",""),
new VasbyhemData("6.15.40 Saker i trapphus och utrymningsvägar.docx","Rutin","Alexander.Gustafsson@vasbyhem.se","Förvaltningsområde Väst","K0 - Allmän","","",""),
new VasbyhemData("6.15.42 Skadedjur.docx","Rutin","Daniel.Aronson@vasbyhem.se","Förvaltningsområde Centrala","K0 - Allmän","","",""),
new VasbyhemData("6.15.43 Skador vid brand.docx","Rutin","Nicklas.Chrysong@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.15.44 Stoppad lägenhet.docx","Rutin","Eddie.Laakso@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.15.46 Tillsyn garage, p-plats.docx","Rutin","Jenny.Welch@vasbyhem.se","Utemiljö","K0 - Allmän","","",""),
new VasbyhemData("6.15.49 Rondering Utemiljövärd.docx","Rutin","Jenny.Welch@vasbyhem.se","Utemiljö","K0 - Allmän","","","9001"),
new VasbyhemData("6.15.50 Vattenskador.docx","Rutin","John.Linder@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.15.51 Städkontroll vid inflytt.docx","Rutin","Eddie.Laakso@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.15.52 Välkomstbesök .docx","Rutin","Daniel.Aronson@vasbyhem.se","Förvaltningsområde Centrala","K0 - Allmän","","",""),
new VasbyhemData("6.15.52.1 Checklista Välkomstbesök.docx","Checklista","Daniel.Aronson@vasbyhem.se","Förvaltningsområde Centrala","K0 - Allmän","","",""),
new VasbyhemData("6.15.54 Tjänstebilar.docx","Rutin","Alexander.Gustafsson@vasbyhem.se","Förvaltningsområde Väst","K0 - Allmän","","",""),
new VasbyhemData("6.15.56 Arbetskläder.docx","Rutin","Daniel.Aronson@vasbyhem.se","Förvaltningsområde Centrala","K0 - Allmän","","",""),
new VasbyhemData("6.15.58 Checklista Inköp av personbil.docx","Checklista","Alexander.Gustafsson@vasbyhem.se","Förvaltningsområde Väst","K0 - Allmän","","",""),
new VasbyhemData("6.15.59 Skötsel och besiktning av lekplatser.docx","Rutin","Jenny.Welch@vasbyhem.se","Utemiljö","K0 - Allmän","","",""),
new VasbyhemData("6.15.61 Rutin Regler för flaggning.docx","Rutin","Jenny.Welch@vasbyhem.se","Utemiljö","K0 - Allmän","","",""),
new VasbyhemData("6.15.62 Rutin Tillval .docx","Rutin","hanna.nyberg@vasbyhem.se","Förvaltning Stab","K0 - Allmän","","",""),
new VasbyhemData("6.15.63 Rutin Entreprenörsuppföljning.docx","Rutin","Alexander.Gustafsson@vasbyhem.se","Förvaltningsområde Väst","K0 - Allmän","","",""),
new VasbyhemData("6.15.64 Rutin Underhållbesiktning Underhållsbeställning.docx","Rutin","Alexander.Gustafsson@vasbyhem.se","Förvaltningsområde Väst","K0 - Allmän","","",""),
new VasbyhemData("6.15.65 Administration kring farligt avfall (checklista).docx","Checklista","Daniel.Aronson@vasbyhem.se","Förvaltningsområde Centrala","K0 - Allmän","","",""),
new VasbyhemData("6.15.66 Körjournal.docx","Rutin","Alexander.Gustafsson@vasbyhem.se","Förvaltningsområde Väst","K0 - Allmän","","",""),
new VasbyhemData("6.15.69 Men i boende Ersättnings skador.docx","Rutin","Daniel.Aronson@vasbyhem.se","Förvaltningsområde Centrala","K0 - Allmän","","",""),
new VasbyhemData("6.15.7 Serviceorder och bokade tider.docx","Rutin","Alexander.Gustafsson@vasbyhem.se","Förvaltningsområde Väst","K0 - Allmän","","",""),
new VasbyhemData("6.15.71 Åtgärder Material och Ytskikt (Blankett).docx","Blankett","Nicklas.Chrysong@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.15.72  Rutin Hantering större omfattande skador.docx","Rutin","Nicklas.Chrysong@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.15.8 Backup vid oplanerad och planerad frånvaro .docx","Rutin","Daniel.Aronson@vasbyhem.se","Förvaltningsområde Centrala","K0 - Allmän","","",""),
new VasbyhemData("6.16.1 Rutin Boendedialoger.docx","Rutin","Daniel.Aronson@vasbyhem.se","Förvaltningsområde Centrala","K0 - Allmän","","",""),
new VasbyhemData("6.16.10 Rutin + checklista Anmälan vis misstankte om våld eller brott i nära relation.docx","Rutin","Therese.Fleetwood@vasbyhem.se","Trygghet ＆ Säkerhet","K0 - Allmän","","",""),
new VasbyhemData("6.16.2 Rutin Mobila kontoret.docx","Rutin","Benjamin.Jolsen@vasbyhem.se","Trygghet ＆ Säkerhet","K0 - Allmän","","",""),
new VasbyhemData("6.16.3 Rutin Trivselaktiviteter.docx","Rutin","Benjamin.Jolsen@vasbyhem.se","Trygghet ＆ Säkerhet","K0 - Allmän","","",""),
new VasbyhemData("6.16.4 Sanitär olägenhet.docx","Rutin","Therese.Fleetwood@vasbyhem.se","Trygghet ＆ Säkerhet","K0 - Allmän","","",""),
new VasbyhemData("6.16.5 Störning.docx","Rutin","Therese.Fleetwood@vasbyhem.se","Trygghet ＆ Säkerhet","K0 - Allmän","","",""),
new VasbyhemData("6.16.6 Trygghetskamera.docx","Rutin","Therese.Fleetwood@vasbyhem.se","Trygghet ＆ Säkerhet","K0 - Allmän","","",""),
new VasbyhemData("6.16.7 Trygghetsvandring.docx","Rutin","Emelie.wallen@vasbyhem.se","Trygghet ＆ Säkerhet","K0 - Allmän","","",""),
new VasbyhemData("6.16.9 Oriktiga hyresförhållanden.docx","Rutin","Saija.Jonsson@vasbyhem.se","Trygghet ＆ Säkerhet","K0 - Allmän","","",""),
new VasbyhemData("6.17.1 Checklista Utlämning av allmänna handlingar.docx","Checklista","sofi.sterner@vasbyhem.se","Affärsstöd Stab","K0 - Allmän","","",""),
new VasbyhemData("6.18.3 Instruktion Hantering av möbler och avfall.källsortering Centralvägen 1 kontor.docx","Instruktion","linda.selberg@vasbyhem.se","Kundcenter","K0 - Allmän","","",""),
new VasbyhemData("6.2.1 Identifiering av bindande miljörelaterade krav.docx","Rutin","Azarina.Backstrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.20. Rutin utdelning av IT utrustning med kvittens.docx","Rutin","Julia.Hammar@vasbyhem.se","Affärsstöd Stab","K0 - Allmän","","",""),
new VasbyhemData("6.20.1  Rutin Digitalt Signeringsverktyg (Netpublicator).docx","Rutin","Julia.Hammar@vasbyhem.se","Affärsstöd Stab","K0 - Allmän","","",""),
new VasbyhemData("6.20.10 Rutin för programförändring.docx","Rutin","Julia.Hammar@vasbyhem.se","Affärsstöd Stab","K0 - Allmän","","",""),
new VasbyhemData("6.20.11 Instruktion installation dator.docx","Instruktion","Julia.Hammar@vasbyhem.se","Affärsstöd Stab","K0 - Allmän","","",""),
new VasbyhemData("6.20.12 Rutin incidentrapportering IT.docx","Rutin","Julia.Hammar@vasbyhem.se","Affärsstöd Stab","K0 - Allmän","","",""),
new VasbyhemData("6.20.13 Instruktion incidenthantering IT.docx","Instruktion","Julia.Hammar@vasbyhem.se","Affärsstöd Stab","K0 - Allmän","","",""),
new VasbyhemData("6.20.2 Instruktion Digitalt signeringsverktyg (Netpublicator).docx","Instruktion","Julia.Hammar@vasbyhem.se","Affärsstöd Stab","K0 - Allmän","","",""),
new VasbyhemData("6.20.4 Rutin för lösenordshantering.docx","Rutin","Julia.Hammar@vasbyhem.se","Affärsstöd Stab","K0 - Allmän","","",""),
new VasbyhemData("6.20.5 Rutin behörigheter system.docx","Rutin","Julia.Hammar@vasbyhem.se","Affärsstöd Stab","K0 - Allmän","","",""),
new VasbyhemData("6.20.7 Förvaltningsplan IT Väsbyhem.docx","Rutin","Julia.Hammar@vasbyhem.se","Affärsstöd Stab","K0 - Allmän","","",""),
new VasbyhemData("6.20.8 Instruktion installation mobiltelefon.docx","Instruktion","Julia.Hammar@vasbyhem.se","Affärsstöd Stab","K0 - Allmän","","",""),
new VasbyhemData("6.20.9 Instruktion SMS via serviceorder Vitec TF.docx","Instruktion","Jonas.Ryhn@vasbyhem.se","Affärsstöd Stab","K0 - Allmän","","",""),
new VasbyhemData("6.3.1.1 Organisationsplan - utan personnamn.pptx","Rutin","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.3.1.1 Organisationsplan på Väsbyhem, med personnamn.xlsx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.1.3 Miljöorganisation på Väsbyhem.docx","Rutin","Azarina.Backstrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.3.1.4 Processägarrollen.docx","Rutin","hanna.nyberg@vasbyhem.se","Förvaltning","K0 - Allmän","","",""),
new VasbyhemData("6.3.2 Befattningsbeskrivning  Fastighetsadministratör.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Affärsstödschef.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Affärsutvecklingschef.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Arkivarie .docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Avtalscontroller.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Besiktnings- och planeringsledare.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Bolagsjurist.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Byggledare.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Chefsassistent.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Digital marknadskommunikatör.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Drifttekniker.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Ekonomi- och lönehandläggare.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Fastighetsekonom.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Fastighetsingenjör - Brand.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Fastighetsingenjör - Energi.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Fastighetsingenjör.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Fastighetsutvecklingschef.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Felanmälan.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Förvaltningsadministratör.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Förvaltningschef.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning HR-ansvarig.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning HR-generalist.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Hyresadministratör.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Hållbarhetssamordnare.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Informatör.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Installationsledare.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning IT-samordnare.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Kommersiell förvaltare.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Kontorsvärd.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Kundcenterchef.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Kundcentermedarbetare.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Kundcentersamordnare.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Kundservice- och Uthyrningschef.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Kvartersvärd.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Marknads- och hållbarhetschef.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Marknads- och kommunikationschef.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Marknadsförare.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Marknadsstrateg.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Ombyggnadssamordnare.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Områdeschef.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Projektledare.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Projektutvecklare.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Redovisningschef.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Redovisningsekonom.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Systemadministratör.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Säkerhetssamordnare.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Teknik- och Underhållschef.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Trygghets- och säkerhetschef.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Trygghetssamordnare.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Upphandlingssamordnare.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Utemiljöchef.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Utemiljösamordnare.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Utemiljövärd.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Uthyrare Bostäder.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Uthyrningschef.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Uthyrningssamordnare.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Utredare.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning VD.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Verksamhetscontroller.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Verksamhetsutvecklare.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.2 Befattningsbeskrivning Vice VD samt HR- Marknad- och hållbarhetschef.docx","Dokumentmall","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.3.3.10 Fullmakt VD (blankett).docx","Blankett","Frida.Bodin@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.3.3.11 Fullmakt Vice VD (blankett).docx","Blankett","Frida.Bodin@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.3.3.12 Fullmakt Avdelningschef (blankett).docx","Blankett","Frida.Bodin@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.3.3.13 Delegation brandskyddsansv till brandskyddskontr Centrala.docx","Blankett","Ulf.Larsen@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.3.3.14 Delegation brandskyddsansv till brandskyddskontr Utemiljö 2.docx","Blankett","Ulf.Larsen@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.3.3.3 Brandskyddsorganisation.docx","Blankett","Ulf.Larsen@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.3.3.4 Delegation VD till brandskyddsansvarig.docx","Blankett","Ulf.Larsen@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.3.3.5 Delegation brandskyddsansv till brandskyddskontr Öst.docx","Blankett","Ulf.Larsen@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.3.3.6 Delegation brandskyddsansv till brandskyddskontr Väst.docx","Blankett","Ulf.Larsen@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.3.3.7 Delegation brandskyddsansv till brandskyddskontr Utemiljö 1.docx","Blankett","Ulf.Larsen@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.3.3.8 Delegation brandskyddsansv till brandskyddsombud.docx","Blankett","Ulf.Larsen@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.4.1 Avvikelse, korrigerande åtgärd och förbättringsförslag.docx","Rutin","hanna.nyberg@vasbyhem.se","Förvaltning Stab","K0 - Allmän","","",""),
new VasbyhemData("6.4.1.1 Förbättring (blankett).docx","Blankett","hanna.nyberg@vasbyhem.se","Förvaltning Stab","K0 - Allmän","","",""),
new VasbyhemData("6.4.2 Väsbyhems betydande miljöaspekter - kortfattade regler för leverantörer.docx","Rutin","Azarina.Backstrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.4.3 Rutin Affärsplan och Verksamhetsplaner.docx","Rutin","Frida.Bodin@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.5.1 Uthyrning kommersiella lokaler.docx","Rutin","Stina.KjetselbergSalmen@vasbyhem.se","Förvaltning Stab","K0 - Allmän","","",""),
new VasbyhemData("6.6.1 Rutin Frånvaroanmälan.docx","Rutin","Elin.bejegard@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.6.11 Rutin Anmälan om kränkande särbehandling.docx","Rutin","Elin.bejegard@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.6.12 Rutin Internrekrytering.docx","Rutin","Victoria.brantestrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.6.13 Introduktionsprogram vid nyanställning.docx","Rutin","Victoria.brantestrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.6.16 Rutin Återgång till arbetet.docx","Rutin","Elin.bejegard@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.6.17 Rutin Arbetsanpassning.docx","Rutin","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.6.18 Medarbetare avlider.docx","Rutin","Victoria.brantestrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.6.2 Rutin Färdolycksfall Olycksfall Riskobservation och Tillbud.docx","Rutin","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.6.2.2 Anmälan och hantering av färdolycksfall, olycksfall, tillbud och riskobservation.docx","Rutin","Victoria.brantestrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.6.2.2 Instruktion anmälan och hantering av färdolycksfall, olycksfall, tillbud och riskobservation.docx","Instruktion","Victoria.brantestrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.6.3 Rutin Behovs- och kravanalys inför rekrytering.docx","Rutin","Victoria.brantestrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.6.4 Anmälan om bisyssla (mall).docx","Blankett","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.6.5 Rekrytering - Intern annons (mall).docx","Blankett","Victoria.brantestrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.6.6 Underlag till anställningsavtal (mall).docx","Blankett","Victoria.brantestrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.6.8 Rutin Upprepad korttidsfrånvaro.docx","Rutin","Harminder.Mankoo@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.6.9 Sista anställningsdag för medarbetare (checklista).docx","Checklista","Victoria.brantestrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.7.1 Rutin Dokumenthantering.docx","Rutin","hanna.nyberg@vasbyhem.se","Förvaltning Stab","K0 - Allmän","","",""),
new VasbyhemData("6.7.10 Intressentkravsanalys Väsbyhem.xlsx","Dokumentmall","Azarina.Backstrom@vasbyhem.se","HMH Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.7.11 Arkivbeskrivning.docx","Dokumentmall","sofi.sterner@vasbyhem.se","Affärsstöd Stab","K0 - Allmän","","",""),
new VasbyhemData("6.7.12 Hanteringsanvisningar för arkivering Väsbyhem.xlsx","Dokumentmall","sofi.sterner@vasbyhem.se","Affärsstöd Stab","K0 - Allmän","","",""),
new VasbyhemData("6.7.13 Logg interna revisioner.docx","Blankett","hanna.nyberg@vasbyhem.se","Förvaltning Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.7.14 Logg interna lagkravskontroller.docx","Rutin","hanna.nyberg@vasbyhem.se","Förvaltning Stab","K0 - Allmän","","",""),
new VasbyhemData("6.7.15 Logg revisioner leverantörer.docx","Blankett","hanna.nyberg@vasbyhem.se","Förvaltning Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.7.16 Logg lagkravskontroller leverantörer.docx","Rutin","hanna.nyberg@vasbyhem.se","Förvaltning Stab","K0 - Allmän","","",""),
new VasbyhemData("6.7.17 Intern kontroll.docx","Rutin","hanna.nyberg@vasbyhem.se","Förvaltning Stab","K0 - Allmän","","",""),
new VasbyhemData("6.7.18 Checklista Information till systemförvaltare.xlsx","Dokumentmall","Victoria.brantestrom@vasbyhem.se","HMH Stab","K0 - Allmän","","",""),
new VasbyhemData("6.7.2 Instruktion Revidering av dokument.docx","Instruktion","hanna.nyberg@vasbyhem.se","Förvaltning Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.7.23 Intern revision.docx","Rutin","hanna.nyberg@vasbyhem.se","Förvaltning Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.7.23.1 Revisionsrapport (mall).docx","Blankett","hanna.nyberg@vasbyhem.se","Förvaltning Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.7.23.2 Avvikelserapport vid intern revision (mall).docx","Blankett","hanna.nyberg@vasbyhem.se","Förvaltning Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.7.23.3 Granskningsmatris vid intern revision (mall).xlsx","Dokumentmall","hanna.nyberg@vasbyhem.se","Förvaltning Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.7.23.3 Granskningsmatris vid intern revision Affärsstöd Kundgrupp.xlsx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.7.23.3 Granskningsmatris vid intern revision Affärsstöd Kundgrupp.xlsx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.7.23.3 Granskningsmatris vid intern revision Fastighetsutveckling 230216.xlsx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.7.23.3 Granskningsmatris vid intern revision Fastighetsutveckling.xlsx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.7.23.3 Granskningsmatris vid intern revision för Affärsutv Social Hållbarhet.xlsx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.7.23.3 Granskningsmatris vid intern revision Förvaltning, 2021 - 2023.xlsx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.7.23.3 Granskningsmatris vid IR o LK, Affärsstöd Redovisning och Ekonomi.xlsx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.7.23.3 Granskningsmatris vid IR o LK. Förvaltning Teknik ＆ Underhåll.xlsx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.7.24 Översiktlig plan för revisioner och kontroll av efterlevnad av bindande krav (tre år).docx","Dokumentmall","hanna.nyberg@vasbyhem.se","Förvaltning Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.7.26 Revision av leverantör.docx","Instruktion","hanna.nyberg@vasbyhem.se","Förvaltning Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("6.7.5 Checklista chefer VLS.docx","Checklista","hanna.nyberg@vasbyhem.se","Förvaltning Stab","K0 - Allmän","","",""),
new VasbyhemData("6.7.6 Rutin Information vid arbeten som berör hyresgäst.docx","Rutin","Catrine.Westerberg@vasbyhem.se","Marknad ＆ Kommunikation","K0 - Allmän","","",""),
new VasbyhemData("6.7.8 Rutin Trycksaker.docx","Rutin","Catrine.Westerberg@vasbyhem.se","Marknad ＆ Kommunikation","K0 - Allmän","","",""),
new VasbyhemData("6.7.9 Rutin Giveaways.docx","Rutin","Catrine.Westerberg@vasbyhem.se","Marknad ＆ Kommunikation","K0 - Allmän","","",""),
new VasbyhemData("6.8.1 Program för kvalitet och miljö.docx","Rutin","martin.sterner@vasbyhem.se","Fastighetsutveckling","K0 - Allmän","","",""),
new VasbyhemData("6.8.1.1 Bil 1 Projekteringsprogram (mall).docx","Blankett","martin.sterner@vasbyhem.se","Fastighetsutveckling","K0 - Allmän","","",""),
new VasbyhemData("6.8.1.2 Bil 2 Checklista för fuktsäkerhetsprojektering.docx","Checklista","martin.sterner@vasbyhem.se","Fastighetsutveckling","K0 - Allmän","","",""),
new VasbyhemData("6.8.1.3 Bil 3 Källsorteringsrum.docx","Rutin","martin.sterner@vasbyhem.se","Fastighetsutveckling","K0 - Allmän","","",""),
new VasbyhemData("6.8.1.3.1 Beräkning avfallsmängder (mall ).xlsx","Dokumentmall","Daniel.Aronson@vasbyhem.se","Förvaltningsområde Centrala","K0 - Allmän","","",""),
new VasbyhemData("6.8.1.3.2 Mått på kärl i källsorteringsrum (mall).xlsx","Dokumentmall","Daniel.Aronson@vasbyhem.se","Förvaltningsområde Centrala","K0 - Allmän","","",""),
new VasbyhemData("6.8.1.4 Bil 4 Markbehållare för mat- och-eller restavfall.docx","Rutin","martin.sterner@vasbyhem.se","Fastighetsutveckling","K0 - Allmän","","",""),
new VasbyhemData("6.8.1.5 Bil 5 Checklista för arbetsmiljörisker vid projektering.docx","Checklista","martin.sterner@vasbyhem.se","Fastighetsutveckling","K0 - Allmän","","",""),
new VasbyhemData("6.8.1.6 Bil 6 Byggande i miljömässig framkant, försättsblad.docx","Rutin","martin.sterner@vasbyhem.se","Fastighetsutveckling","K0 - Allmän","","",""),
new VasbyhemData("6.8.3 Rutin Ändrad användning av utrymmen under förvaltningsskede.docx","Rutin","martin.sterner@vasbyhem.se","Fastighetsutveckling","K0 - Allmän","","",""),
new VasbyhemData("6.8.4 Rutin Planering byggherrekostnader.docx","Rutin","martin.sterner@vasbyhem.se","Fastighetsutveckling","K0 - Allmän","","",""),
new VasbyhemData("6.8.5 Rutin förnyelse och stambyte.docx","Rutin","elin.gustafsson@vasbyhem.se","Fastighetsutveckling","K0 - Allmän","","",""),
new VasbyhemData("6.9.1 Rutin köldmedia.docx","Rutin","Linus.Hagestal@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.9.1.1 Anläggningslista köldmedieaggregat Väsbyhem.xlsx","Dokumentmall","Linus.Hagestal@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.9.11 Rutin Tillfälligt stoppade lägenheter.docx","Rutin","Eddie.Laakso@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.9.3 Rutin vattenprover.docx","Rutin","Ulf.Larsen@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.9.4 Rutin asbest rörledningar.docx","Rutin","Ulf.Larsen@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.9.5 Rutin kontakt vid tekniskt fel i lägenhet.docx","Rutin","Ulf.Larsen@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("6.9.6 Rutin för kalibrering av instrument.docx","Rutin","Linus.Hagestal@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","","14001"),
new VasbyhemData("6.9.7 Rutin Nyckel- och låshantering.docx","Rutin","Magnus.Andersson@vasbyhem.se","Teknik ＆ Underhåll","K0 - Allmän","","",""),
new VasbyhemData("AK4, om granen i Stationsparken, 200103.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("Avtal men i boende.pdf","Dokumentmall","Ulrica.Nordeberg@vasbyhem.se","Redovisning ＆ Ekonomi","K0 - Allmän","","",""),
new VasbyhemData("Bil 1, Nya och reviderade bindande krav, ledn genomgång av VLS 220405.docx","Protokoll","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("Blankett Avarn Larmunderlag Personlarm.docx","Blankett","Peyman.Rezapour@vasbyhem.se","Trygghet ＆ Säkerhet","K0 - Allmän","","",""),
new VasbyhemData("Blankett Beställning Marknad (6.16.8 ).docx","Blankett","caroline.sjolund@vasbyhem.se","Marknad ＆ Kommunikation","K0 - Allmän","","",""),
new VasbyhemData("Blankett Bokföringsrorder 3L (6.14.2).xlsx","Dokumentmall","Annsofie.Lindblad@vasbyhem.se","Redovisning ＆ Ekonomi","K0 - Allmän","","",""),
new VasbyhemData("Blankett Förbättring (3.5.1.1).docx","Blankett","hanna.nyberg@vasbyhem.se","Förvaltning Stab","K0 - Allmän","","",""),
new VasbyhemData("Blankett mall begäran om tillträde till lägenhet.docx","Blankett","Saija.Jonsson@vasbyhem.se","Trygghet ＆ Säkerhet","K0 - Allmän","","",""),
new VasbyhemData("Blankett Utkvittering av nycklar entreprenörer (6.12.3).docx","Blankett","linda.selberg@vasbyhem.se","Kundcenter","K0 - Allmän","","",""),
new VasbyhemData("Flik 1 Uthyrningspolicy.doc","Policy","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 10 Sena hyresbetalare.doc.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 11 Störningsärenden.doc.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 12 Lägenhetsbyte.doc.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 13 Övergivna lägenheter sid 2.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 13 Övergivna lägenheter.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 14 Övertagande av köplats.doc.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 15 Uppsagda, uppgörelser i sista minuten.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 16 Skuldsanering.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 17 God man.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 18 Överföring kontrakt på närstående.doc.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 18 Överföring_Separation från kontrakt sid 2.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 19 Spärr av bostadssökande-2.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 2 Ansvarsfördelning uthyrningsärenden.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 20 Ungdomsboende.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 21 Seniorboende och handikapplägenheter-2.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 22 Försöksboende-2.doc.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 23 Lägenheter till företag-2.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 24 Rökfritt boende-2.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 25 Trygghetsboende-2.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 26 Allergiboende-2.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 27 Evakueringslägenheter-2.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 28 Studentboende.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 29 Paraboler och antenner-2.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 3 Arbetsflöde inom uthyrningen.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 4 Arbetsflöde ombildning bostadsrätt.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 5  Uthyrning p-platser ny.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 5  Uthyrning p-platser.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 6 Regler för godkännande 2018.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 6 Regler för godkännande sid 2.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 6 Regler för godkännande.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 7 Uppsägningstider.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 7 Uppsägningstider.docx","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 8 Andrahandsuthyrning.doc.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Flik 9 Kunder med skyddad identitet.doc.doc","Rutin","Annica.Tuomela@vasbyhem.se","Uthyrning","K0 - Allmän","","",""),
new VasbyhemData("Granskningsmatris int rev och lagkravskontroll, Förvaltning.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("Granskningsmatris vid int rev, Fastighetsutv t o m 2019.xlsx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("Granskningsmatris vid intern revision för Affärsutv Social Hållbarhet.xlsx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("Granskningsmatris vid intern revision Förvaltning, 2017 - 2019.xlsx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("Granskningsmatris vid intern revision Förvaltning, 2021 - 2023.xlsx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("Granskningsmatris vid intern revision Ledningsgrupp.xlsx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("Granskningsmatris vid IR o LK. Förvaltn Tekn o UH 220408.xlsx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("Granskningsmatris vid IR o LK. Ledning 220927.xlsx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("Granskningsmatris vid IR o LK. Stab marknad och hållbarhet 220516.xlsx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("Granskningsmatris vid IR och LK, Affärsutveckling, Kundgrupp.xlsx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("Granskningsmatris vid IR och LK, Affärsutveckling, Stab och Ekonomi.xlsx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("Granskningsmatris vid IR och LK, Högsta ledningen.xlsx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("Granskningsmatris, Affärsutveckling, Stab o Ekonomi.xlsx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("Granskningsmatris, Affärsutvecklingsavdelningen.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("Granskningsmatris, Fastighetsutvecklingsavdelningen.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("Granskningsmatris, IR och LK, Adm avd.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("Granskningsmatris, IR och LK, Administrativa avd, Kansli.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("Granskningsmatris, IR och LK, Förvaltning.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("Granskningsmatris, IR och LK, Förvaltningen, 2015.docx","Dokumentmall","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("Mall Avvikelserapport vid intern revision (6.7.23.2).docx","Blankett","hanna.nyberg@vasbyhem.se","Förvaltning Stab","K0 - Allmän","","","9001;14001"),
new VasbyhemData("Mall Beräkning avfallsmängder (6.8.1.3.1 ).xlsx","Blankett","Daniel.Aronson@vasbyhem.se","Förvaltningsområde Centrala","K0 - Allmän","","",""),
new VasbyhemData("Mall Mått på kärl i källsorteringsrum (6.8.1.3.2).xlsx","Dokumentmall","Daniel.Aronson@vasbyhem.se","Förvaltningsområde Centrala","K0 - Allmän","","",""),
new VasbyhemData("Mall Riskbedömning (6.6.15).docx","Blankett","sofi.sterner@vasbyhem.se","HMH Stab","K0 - Allmän","","","")*/
new VasbyhemData("1.0 Processkarta, översikt med nummer.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("1.0 Processkartor på Väsbyhem m plats för en extra process.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("1.0 Processkartor på Väsbyhem.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("1.0 Processkartor på Väsbyhem.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.10.13 Karta Oljeavskiljare Hammarbyväg 18.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.12 Beställning internt.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.13 Bomöte.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.14 Cykelrensning.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.15 Rondering Drift.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.16 Driftstörning.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.17 Entreprenörsuppföljning.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.18 Tömma felaktigt tagna eller kvarlämnade förråd.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.19 Felanmälan ute.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.2 Is och snö.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.20 Felanmälan via webb.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.21 Felanmälan via mejl och telefon.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.22 Felparkerade bilar och bortforsling.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.23 Förrådsskötsel.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.24 Garanti.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.25 Infoblad.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.26 Infotavla i trapphus.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.27 Inglasning av balkong.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.28 Kalla lägenheter.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.29 Klagomålshantering.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.3 Besiktning vid avflytt.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.30 Kontroll av faktura.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.31 Kvalitetsundersökning.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.32 Lappar.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.33 Låsbyte.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.34 Misstanke om dödsfall.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.35 Oriktiga hyresförhållanden.docx","Rutin","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.35 Oriktiga hyresförhållanden.vsdx","Processritning","Saija.Jonsson@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.36 Namntavlor.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.37 Obehörig i allmänna utrymmen.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.38 Paraboler.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.39 Rondering Kvartersvärd.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.4 Inflytt.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.40 Saker i trapphus och utrymningsvägar.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.42 Skadedjur.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.43 Skador vid brand.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.44 Stoppad lägenhet.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.46 Tillsyn garage, p-plats.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.48 Underhållsbesiktning.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.48 Underhållsbeställning.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.49 Rondering Utemiljövärd.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.5 Fakturering.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.50 Vattenskador.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.6 Tillval.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.62  Tillval Visio.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.7 Serviceorder och bokade tider.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.8 Backup vid semester eller föräldraledighet.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.9 Backup vid sjukfrånvaro.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.15.9 Checklista systemrodering egenkontrollprogram kvartersvärd Visiokarta.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.16.4 Sanitär olägenhet.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.16.5 Störning.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","",""),
new VasbyhemData("6.16.7 Trygghetsvandring.vsdx","Processritning","hanna.nyberg@vasbyhem.se","","K0 - Allmän","","","")
            };
            return ret;
        }

        public VasbyhemData(string DocumentName, string DocumentType, string DocumentOwner, string AvdelningEnhet, string Klassificering, string Process, string Sekretess, string ISOStandard)
        {
            this.DocumentName = DocumentName;
            this.DocumentType = DocumentType;
            this.DocumentOwner = DocumentOwner;//title as well
            this.AvdelningEnhet = AvdelningEnhet;//nno need
            this.Klassificering = Klassificering;
            this.Process = Process;
            this.Sekretess = Sekretess;
            this.ISOStandard = ISOStandard; 
        }
    }
}
